### ISSUE TITLE
Compilation problems with 3.3.2-RC nightly

### ISSUE THREAD

**Issue by WojciechMazur** [alterationx10/opinionated-zio#7]
Hey, I've found this project after failure in Scala 3 Open Community Build.  
The problematic code is present in this lines: https://github.com/alterationx10/opinionated-zio/blob/ed25efaab3c2ed784500280175f6b1e1177e0081/opinions/src/main/scala/opinions/ZIO.scala#L70-L91
After some of the latest typer improvements of Scala typer the project would no longer compile. The minimization of this problem can be found in: https://github.com/lampepfl/dotty/issues/18277 
In Scala 3.3.0 and 3.3.1 the `deps.toArray` failed to correctly infer type of `p.MirrorElemTypes` and used `Object` instead. This allow to use `ClassTag[Object]` to allow for conversion of list to array. In later, nightly versions of compiler the infered type is more narrowed, and though `ClassTag[Object]` can no longer be applied.  

As the compiler team have concluded this code should not compile, it is not following the language spec and should be rewritten in the future.

**Comment by alterationx10** [comment]
@WojciechMazur Thank you for bringing this to my attention!

I was able to fix the issue by casting to a `List[Object]` before calling toArray.

As you mentioned in https://github.com/lampepfl/dotty/issues/18277, I only wanted to create an instance of `p` using `p.fromProduct`... A `Tuple.fromList` would be very useful! I'm trying to gather constructor arguments, so if I had something that needed an `A`, `B`, and a `C`, I'm trying to store them in a `List[A | B | C]`, but I don't feel like I know how to cleanly get a `ClassTag[A | B | C]` in the current implementation.

This discussion would probably be too much for this issue, but where would be a good place to ask about what would be a more proper fix?
